/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import control.PersistenciaJPA;
import java.util.logging.Level;
import java.util.logging.Logger;
import model.Produto;
import model.Tipo;
import model.Usuario;

/**
 *
 * @author Usuário
 */
public class PrincipalAdmJF extends javax.swing.JFrame {
    PersistenciaJPA jpa;

    /**
     * Creates new form PrincipalAdmJF
     */
    public PrincipalAdmJF() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        minCliente = new javax.swing.JMenuItem();
        minAdm = new javax.swing.JMenuItem();
        minProduto = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jMenu1.setText("Cadastrar");

        minCliente.setText("Cliente");
        minCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minClienteActionPerformed(evt);
            }
        });
        jMenu1.add(minCliente);

        minAdm.setText("Administrador");
        minAdm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minAdmActionPerformed(evt);
            }
        });
        jMenu1.add(minAdm);

        minProduto.setText("Produto");
        minProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minProdutoActionPerformed(evt);
            }
        });
        jMenu1.add(minProduto);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 593, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 335, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void minClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minClienteActionPerformed
        CadastroUsuarioJF tela = new CadastroUsuarioJF(this, true);
        tela.setTipoUsuario(Tipo.CLIENTE);
        tela.setVisible(true);
         Usuario novoUsuario= tela.getUsuario();
        if(novoUsuario != null){
            try {
                if(jpa == null){
                    jpa = new PersistenciaJPA();
                }
                jpa.persist(novoUsuario);
            } catch (Exception ex) {
                Logger.getLogger(PrincipalJF.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_minClienteActionPerformed

    private void minAdmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minAdmActionPerformed
        CadastroUsuarioJF tela = new CadastroUsuarioJF(this, true);
        tela.setTipoUsuario(Tipo.ADM);
        tela.setVisible(true);
        
        Usuario novoUsuario= tela.getUsuario();
        if(novoUsuario != null){
            try {
                if(jpa == null){
                    jpa = new PersistenciaJPA();
                }
                jpa.persist(novoUsuario);
            } catch (Exception ex) {
                Logger.getLogger(PrincipalJF.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_minAdmActionPerformed

    private void minProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minProdutoActionPerformed
        CadastroProdutoJD telaProduto = new CadastroProdutoJD(this, true);
        telaProduto.setVisible(true);
        
         Produto novoProduto = telaProduto.getProduto();
        if(novoProduto != null){
            try {
                if(jpa == null){
                    jpa = new PersistenciaJPA();
                }
                jpa.persist(novoProduto);
            } catch (Exception ex) {
                Logger.getLogger(PrincipalJF.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_minProdutoActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalAdmJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalAdmJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalAdmJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalAdmJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalAdmJF().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem minAdm;
    private javax.swing.JMenuItem minCliente;
    private javax.swing.JMenuItem minProduto;
    // End of variables declaration//GEN-END:variables
}
